apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ydyyqjoi8-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-44d7f729ba.keu7.p3.openshiftapps.com/rhtap/rhtap-qe:63e40d42755bd246af2f73c98ed39bbb561caeb3@sha256:b8a59a1fd73f62ffec6808e4b44e52a79248725fde6cd5bba7c7b0388d2c5959
          name: container-image
